### PR TITLE
Add pre-commit based linting infrastructure

### PR DESCRIPTION
**Pull request by webknjaz**
This is what a typical Python project uses for linting (partially). I thought it'd be useful, I disabled all the violations that are currently present.

Action items for @samdoran:
* [ ] Go to https://github.com/apps/pre-commit-ci/installations/new
* [ ] Install the app, selecting only this repository in the list
* [ ] (optionally) re-open this PR to get the first status check
* [ ] (optionally, but after the previous item) add the new check to branch protection

### CODE REVIEW

**Comment by webknjaz** [comment]
@samdoran lmk if you're fine with trying this out

**Comment by samdoran** [comment]
I would love to incorporate something like this. It might be a bit more than I want, so I may pare it down after reviewing/merging it.

**Comment by webknjaz** [comment]
Or you could disable stuff post merge. It's specifically set up to not report violations on the current code base.

**Comment by webknjaz** [comment]
> Action items for @samdoran:
> 
>     * [ ]  Go to [github.com/apps/pre-commit-ci/installations/new](https://github.com/apps/pre-commit-ci/installations/new)
> 
>     * [ ]  Install the app, selecting only this repository in the list

Could you also enable the service?

**Pull request merged**
